<?php

namespace Marlinc\AdminBundle\Entity;

use Sonata\ClassificationBundle\Entity\BaseContext;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class Context extends BaseContext
{
    /**
     * @var string $id
     */
    protected $id;

    /**
     * Get id.
     *
     * @return string $id
     */
    public function getId()
    {
        return $this->id;
    }
}
