<?php

namespace Marlinc\AdminBundle\Entity;


use Gedmo\Mapping\Annotation as Gedmo;
use Sonata\ClassificationBundle\Entity\BaseTag;
use Sonata\TranslationBundle\Model\Gedmo\TranslatableInterface;
use Sonata\TranslationBundle\Traits\Gedmo\TranslatableTrait;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class Tag extends BaseTag implements TranslatableInterface
{
    use TranslatableTrait;

    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var string
     * @Gedmo\Translatable
     */
    protected $name;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
}
